//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lumer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LumerEntities : DbContext
    {
        public LumerEntities()
            : base("name=LumerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Plase> Plase { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
    
        public virtual ObjectResult<GetFilmOnWeek_Result> GetFilmOnWeek(Nullable<System.DateTime> weekStart, Nullable<System.DateTime> weekEnd)
        {
            var weekStartParameter = weekStart.HasValue ?
                new ObjectParameter("WeekStart", weekStart) :
                new ObjectParameter("WeekStart", typeof(System.DateTime));
    
            var weekEndParameter = weekEnd.HasValue ?
                new ObjectParameter("WeekEnd", weekEnd) :
                new ObjectParameter("WeekEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFilmOnWeek_Result>("GetFilmOnWeek", weekStartParameter, weekEndParameter);
        }
    }
}
