//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plase
    {
        public int PlaseID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Col { get; set; }
        public Nullable<int> PriseNum { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
